# Generated by Django 5.1.3 on 2024-11-23 09:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_clientinfo_billing_statement_electric_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='total_payed',
            new_name='total_amount_paid',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='net_proceed',
        ),
        migrations.AddField(
            model_name='loan',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 11, 23)),
        ),
        migrations.AddField(
            model_name='loan',
            name='date_paid',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='days_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='days_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='co_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_maker_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='daily_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=datetime.date(2024, 11, 23))),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='server.loan')),
            ],
        ),
    ]
