# Generated by Django 5.1.3 on 2024-12-08 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_loan_date_created_alter_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='work_details',
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 12, 8)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 8)),
        ),
    ]
