# Generated by Django 5.1.3 on 2024-12-10 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_clientinfo_work_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 12, 10)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 10)),
        ),
    ]
