# Generated by Django 5.1.3 on 2025-01-04 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_user_has_loan_alter_loan_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_created',
            field=models.DateField(default=datetime.date(2025, 1, 4)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 4)),
        ),
    ]
