# Generated by Django 5.1.3 on 2024-11-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=20)),
                ('work_details', models.TextField(blank=True, null=True)),
                ('business', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_statement_electric', models.ImageField(blank=True, null=True, upload_to='billing_statements/')),
                ('billing_statement_water', models.ImageField(blank=True, null=True, upload_to='billing_statements/')),
                ('co_maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_maker_clients', to='AgriTrust.client')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_loaned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_term', models.IntegerField(choices=[(3, '3 months'), (6, '6 months'), (9, '9 months'), (12, '12 months')])),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_mode', models.CharField(choices=[('Add-on', 'Add-on'), ('Less', 'Less')], max_length=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_proceed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgriTrust.client')),
            ],
        ),
    ]
