# Generated by Django 5.1.3 on 2024-11-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriTrust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ongoing', 'completed')], default='ongoing', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_payed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
